language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t diliniiresha/docker-myp -f Dockerfile.dev .
script:
  - docker run diliniiresha/docker-myp npm run test -- --coverage