version: 2.1
jobs:
  build:
    docker:
      - image: node:16-alpine
    steps:
      - checkout:
      - run: docker build -t diliniiresha/docker-myp -f Dockerfile.dev .
      - run: docker run diliniiresha/docker-myp npm run test -- --coverage
