version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16-alpine
jobs:
  core:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - vi-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - run: npm run test:ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  eb-demo:
    docker:
      - image: circleci/node:16-alpine
    steps:
      - checkout
      - eb/setup
      - run:
          command:
            eb create diliniiresha
            eb deploy diliniiresha
            eb status
          name: You may now use the EB CLI within this job
workflows:
  version: 2.1
  core:
    elastic-beanstalk-workflow:
      jobs:
        - core:
            filters:
              branches:
                only:
                  - master
        - eb-demo
