version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:16-alpine
    steps:
      - checkout
      - run: docker build -t diliniiresha/docker-myp -f Dockerfile.dev .
  test:
    docker:
      - image: cimg/node:16-alpine
  # context / project UI env-var reference
    steps:
      - checkout
      - run: docker run diliniiresha/docker-myp npm run test -- --coverage

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
