version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16-alpine
        auth:
          username: jayasekaraireshagmailcom
          password: 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
    parallelism: 10
    resource_class: large    
    working_directory: ~/app
    steps:
      - run: docker build -t diliniiresha/docker-myp -f Dockerfile.dev .
