version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16-alpine
jobs:
  core:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - vi-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - run: npm run test:ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          path: .
workflows:
  version: 2
  core:
    jobs:
      - core:
          filters:
            branches:
              only:
                - master
