version: 2.1
jobs:
  build:
    docker:
      - image: node:16-alpine
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PW
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: |
          docker build -t diliniiresha/docker-myp -f Dockerfile.dev .
          docker run diliniiresha/docker-myp npm run test -- --coverage
workflows:
  version: 2
  build-deploy:
    jobs:
      - build

